#!/usr/bin/env python3
"""
Pre-compress the dashboard page into a PROGMEM array.

    python3 tools/gen_page_gz.py            # rewrites src/webpage_gz.h
    python3 tools/gen_page_gz.py --check    # verifies it is current

WHY THIS EXISTS
---------------
Serving the page is what kills the dashboard. Traced inside a failing send:

    healthy   165 KB in   630 ms
    fatal      80 KB in 12002 ms
    fatal      18 KB in 21006 ms

The Arduino WebServer handles ONE client at a time, so those twelve and
twenty-one seconds are time in which nothing else is answered - and a client
gives up after eight. Every request in that window fails, /api/dash included,
which is what "the dashboard is dead" has meant throughout this investigation.

Four attempts to manage that stall all failed: aborting an abandoned send,
pacing the slices, refusing the page when the heap is low, and bounding the
socket timeout. Every one of them tried to handle a 170 KB transfer better.
None of them made the transfer smaller.

gzip does: 170397 bytes becomes about 52000, 3.3x less. A healthy send drops
from 630 ms to roughly 190. At the degraded rate measured above, the whole page
now moves in 7.6 s instead of 25 - under the client's timeout rather than three
times past it - and the window in which the server is blocked shrinks by the
same factor, so there is 3.3x less of it for a request to collide with.

Browsers have handled Content-Encoding: gzip for twenty-five years. The board
does no work at run time: the compressed bytes sit in flash exactly as the
plain ones do.

WHY A COMMITTED HEADER AND NOT A BUILD STEP
-------------------------------------------
A generated file in the build would need the toolchain to have Python, which is
one more thing to go wrong on a machine that is only trying to flash a board.
The header is committed, and run_tests.sh checks it still matches webpage.cpp -
so it cannot drift silently, which is the only real risk of pre-generating.
"""

import argparse
import gzip
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "src", "webpage.cpp")
OUT = os.path.join(ROOT, "src", "webpage_gz.h")


def page_bytes():
    """The page exactly as handleRoot concatenates it."""
    src = open(SRC, encoding="utf-8", errors="replace").read()
    blocks = re.findall(r'R"HTML\((.*?)\)HTML"', src, re.S)
    if not blocks:
        raise SystemExit("no R\"HTML(...)HTML\" blocks in webpage.cpp")
    return "".join(blocks).encode("utf-8")


def render(raw):
    gz = gzip.compress(raw, 9, mtime=0)   # reproducible: no timestamp inside
    digest = hashlib.sha256(raw).hexdigest()[:16]

    lines = []
    lines.append("/* GENERATED by tools/gen_page_gz.py - DO NOT EDIT.")
    lines.append(" *")
    lines.append(" * The dashboard page, gzipped, for Content-Encoding: gzip.")
    lines.append(" *")
    lines.append(" * Serving the page is what kills the dashboard: the server")
    lines.append(" * handles one client at a time, so a stalled 170 KB send")
    lines.append(" * blocks every other request for as long as it lasts -")
    lines.append(" * measured at 12 and 21 seconds, against clients that give")
    lines.append(" * up after 8. Four attempts to manage that stall failed;")
    lines.append(" * this makes the transfer 3.3x smaller instead.")
    lines.append(" *")
    lines.append(" *   plain  %7d bytes" % len(raw))
    lines.append(" *   gzip   %7d bytes   (%.0f%% of the original)"
                 % (len(gz), 100.0 * len(gz) / len(raw)))
    lines.append(" *")
    lines.append(" * PAGE_SRC_SHA is the first 16 hex of the sha256 of the")
    lines.append(" * uncompressed page. run_tests.sh recomputes it from")
    lines.append(" * webpage.cpp and fails if they differ, so this file cannot")
    lines.append(" * quietly go stale against the page it came from.")
    lines.append(" */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append('#define PAGE_SRC_SHA "%s"' % digest)
    lines.append("")
    lines.append("const uint32_t PAGE_GZ_LEN = %d;" % len(gz))
    lines.append("const uint32_t PAGE_RAW_LEN = %d;" % len(raw))
    lines.append("")
    lines.append("const uint8_t PAGE_GZ[] PROGMEM = {")
    for i in range(0, len(gz), 16):
        row = ", ".join("0x%02x" % b for b in gz[i:i + 16])
        lines.append("  %s," % row)
    lines.append("};")
    lines.append("")
    return "\n".join(lines), digest, len(gz)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the header is out of date")
    a = ap.parse_args()

    raw = page_bytes()
    text, digest, gzlen = render(raw)

    if a.check:
        if not os.path.exists(OUT):
            print("  src/webpage_gz.h is missing - run tools/gen_page_gz.py")
            return 1
        have = open(OUT, encoding="utf-8").read()
        m = re.search(r'#define PAGE_SRC_SHA "([0-9a-f]+)"', have)
        if not m or m.group(1) != digest:
            print("  src/webpage_gz.h is STALE: webpage.cpp has changed since "
                  "it was generated")
            print("  run: python3 tools/gen_page_gz.py")
            return 1
        print("  ok   the compressed page matches webpage.cpp")
        return 0

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("  wrote src/webpage_gz.h")
    print("  page %d bytes -> gzip %d bytes  (%.1fx smaller, %.0f%% of the "
          "original)" % (len(raw), gzlen, len(raw) / gzlen,
                         100.0 * gzlen / len(raw)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
